import { makeStyles } from "tss-react/mui";

export default makeStyles()((theme) => ({
  categoryListContainer: {
    display: "-webkit-box",
    overflow: "scroll",
  },
  categoryItem: {
    display: "flex",
    justifyContent: "center",
    height: 120,
    width: 120,
    padding: 10,
    position: "relative",
  },
  categoryImage: {
    height: "100%",
    width: "100%",
    borderRadius: 5,
  },
  categoryName: {
    position: "absolute",
    bottom: 20,
    fontSize: 12,
    fontWeight: "bold",
  },
  br: {
    height: 1,
    width: "100%",
    borderBottom: "1px solid #dcdcdc",
    margin: "10px 0",
  },
  selectedCategory: {
    borderRadius: 8,
    padding: 3,
  },
  noDataMessage: {
    display: "flex",
    justifyContent: "center",
    width: "100%",
    marginTop: 20,
  },
  subCategoryItem: {
    position: "relative",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  subCategoryImage: {
    width: "100%",
  },
  subCategoryName: {
    position: "absolute",
    bottom: 10,
    fontSize: 12,
    fontWeight: "bold",
  },
  productCard: {
    position: "relative",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    border: "1px solid #dcdcdc",
    borderRadius: 5,
    padding: 10,
  },
  productImage: {
    height: 100,
    width: "fit-content",
    marginTop: 10,
  },
  productLabel: {
    display: "flex",
    textAlign: "left",
    width: "100%",
    fontWeight: "bold",
    color: "#000",
    fontSize: 12,
  },
  productDescription: {
    display: "flex",
    width: "100%",
    textAlign: "left",
    fontSize: 10,
  },
  favoriteContainer: {
    position: "absolute",
    top: 10,
    right: 10,
  },
  drawerCartItemsContainer: {
    borderLeft: "1px dashed #dcdcdc",
  },
  productDrawer: {
    padding: 10,
    height: "100%",
  },
  productImageContainer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    height: 140,
    width: 300,
    backgroundColor: "#EEF1F7",
    position: "relative",
  },
  productImagethumbnail: {
    height: 20,
  },
  thumbnailContainer: {
    position: "absolute",
    left: 10,
    top: 10,
  },
  variantContainer: {
    width: 300,
  },
  variantChip: {
    padding: "4px 10px",
    fontSize: 10,
    border: "1px solid #dcdcdc",
    borderRadius: 3,
    margin: 4,
    width: "fit-content",
    cursor: "pointer",
  },
  drawerFieldLabel: {
    fontWeight: "bold",
    fontSize: 12,
    marginTop: 10,
  },
  description: {
    fontSize: 12,
    marginTop: 10,
  },
  itemDescription: {
    display: "flex",
    flexDirection: "row",
    fontWeight: "bold",
    color: "#000",
    fontSize: 14,
  },
  priceContainer: {
    display: "flex",
    justifyContent: "flex-end",
    flexGrow: 1,
  },
  buttonContainer: {
    display: "flex",
    justifyContent: "center",
    marginTop: 20,
  },
  outlinedButton: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: "5px 50px",
    borderRadius: 5,
    border: "1px solid #f00",
    fontSize: 12,
    color: "#f00",
    fontWeight: "bold",
    cursor: "pointer",
  },
  closeIconContainer: {
    flexGrow: 1,
    display: "flex",
    justifyContent: "flex-end",
  },
  cartHeader: {
    display: "flex",
    alignItems: "center",
    backgroundColor: "#F0F3F8",
    height: 40,
    minWidth: 300,
    marginTop: 10,
  },
  cartHeaderText: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#000",
    textAlign: "center",
  },
  saleDescription: {
    fontSize: 10,
  },
  productName: {
    fontSize: 12,
    color: "#000",
    fontWeight: "bold",
  },
  quantity: {
    fontSize: 12,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  price: {
    display: "flex",
    alignItems: "center",
    fontSize: 12,
    color: "#000",
    fontWeight: "bold",
  },
  productColumnContainer: {
    display: "flex",
    flexDirection: "row",
  },
  productLabelsContainer: {
    display: "flex",
    flexDirection: "column",
  },
  cartpProductImage: {
    height: 20,
  },
  cartProductImageContainer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 10,
  },
  cartItemRecord: {
    marginTop: 10,
  },
  removeIconContainer: {
    display: "flex",
    flexGrow: 1,
    alignItems: "center",
    justifyContent: "flex-end",
  },
  filledButton: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: "5px 50px",
    borderRadius: 5,
    fontSize: 12,
    color: "#fff",
    fontWeight: "bold",
    cursor: "pointer",
    backgroundColor: "#f00",
  },
}));
